language: node_js

node_js:
  - node 

sudo: required

before_install:
  - "yarn add coveralls"

after_success:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  email:
    recipients:
      - travis@webentwickler2-0.de
    on_success: change
    on_failure: always
